[package]
name = "yellow-peach"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iterable = "0.4.1"
structopt = { version = "0.3", default-features = false }